### ISSUE TITLE
requirements.txt contains deprecated links

### ISSUE THREAD

**Issue by pomarec** [cznweb/arkos#22]
https://git.coderouge.co/arkOS/mockldap/repository/archive.tar.gz?ref=0.3.0#egg=mockldap-0.3.0
https://git.coderouge.co/arkOS/python-cryptsetup/repository/archive.tar.gz?ref=1.7.2#egg=pycryptsetup-1.7.2

**Comment by peakwinter** [comment]
This is fixed in the `develop` branch and will be merged at the next release! Thanks :)
