### ISSUE TITLE
Roadmap for ArkOS

### ISSUE THREAD

**Issue by axaluss** [cznweb/arkos#3]
It would be great to see where the project stands with regards to features and stability (alpha, beta, release...). A roadmap could provide an overview of the project status.  i.e. an estimate to when "Warning – arkOS and its constituent software are still in development." will disappear from the homepage would help.

**Comment by peakwinter** [comment]
We will now be publishing regular roadmaps on the blog, using Github milestones, and [on the forums too](https://bbs.arkos.io/t/2017-roadmap/2465).
